import Head from "next/head";
import Cursor from "./Cursor";
import LayoutFooter from "./Footer";
import LayoutHeader from "./Header";
import { inter } from "@/datas";
import useLayoutRef from "@/utils/hooks/useLayoutRef";
import dynamic from "next/dynamic";

const DynamicDarkmodeConfig = dynamic(() => import("./DarkmodeConfig"), {
  ssr: false,
});

export default function Layout({ children }: { children: React.ReactNode }) {
  const { layoutRef } = useLayoutRef();
  return (
    <DynamicDarkmodeConfig>
      <div
        ref={layoutRef}
        className={`px-60 opacity-0 animate-fade-in ${inter.variable}`}
        // onAnimationEnd={(e: AnimationEvent<HTMLDivElement>) => {
        //   console.log(e.animationName);
        // }}
      >
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Cursor />
        <LayoutHeader />
        <main className="">{children}</main>
        <LayoutFooter />
      </div>
    </DynamicDarkmodeConfig>
  );
}
