import Head from "next/head";
import Cursor from "./Cursor";
import Background from "./Background";
import SideBar from "./SideBar";
import { useCallback, useContext, useEffect, useState } from "react";
import FullScreenNav from "./FullScreenNav";
import { activateBodyScroll, deActivateBodyScroll } from "../utils/dom";
import { CursorContext } from "@/context/cursor";
import ProjectDetail from "@/Layout/ProjectDetail";
import Memorizing from "./Memorizing";
import { ProjectContext } from "@/context/project";

function DefaultHead() {
  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default function Layout({ children }: { children: React.ReactNode }) {
  const { project } = useContext(ProjectContext);
  const { isScreenBelowLg } = useContext(CursorContext);
  const [navOpen, setNavOpen] = useState(false);

  const openNav = useCallback(() => {
    setNavOpen(true);
    deActivateBodyScroll();
  }, []);

  const closeNav = useCallback(() => {
    setNavOpen(false);
    activateBodyScroll();
  }, []);

  useEffect(() => {
    activateBodyScroll();
  }, []);

  return (
    <>
      <DefaultHead />
      <Background />
      <Memorizing openNav={openNav}>{children}</Memorizing>
      {isScreenBelowLg ? <FullScreenNav navOpen={navOpen} closeNav={closeNav} /> : <SideBar />}
      {project && <ProjectDetail project={project} />}
      <Cursor />
    </>
  );
}
